//
// Created by Paulius on 2019-05-21.
//

#ifndef ANNEALINGOPTIMISATION_FUNCTIONS_H
#define ANNEALINGOPTIMISATION_FUNCTIONS_H

#endif //ANNEALINGOPTIMISATION_FUNCTIONS_H

double funcBooth(double, double);
